server:
  port: 8080

spring:
  application:
    name: app-locales
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/baresdb
    username: postgres
    password: 1c3p.2024..
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
