server:
  port: 8080
  address: 192.168.191.209

spring:
  application:
    name: app-locales
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/baresdb
    username: postgres
    password: 1c3p.2024..
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
